version: 2.1
description: |
    Terratattle
display:
    home_url: https://www.github.com/FrankieSanzica/terratattle-orb/
    source_url: https://www.github.com/FrankieSanzica/terratattle-orb/

jobs:
    terratattle:
        description: |
            This job runs Terratattle.
        parameters:
          github-url:
            description: GitHub URL
            type: string
            default: github.com
        executor: default
        steps:
            - run:
                command: |
                    git clone https://<<parameters.github-url>>/servicing-sre/terratattle .
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    python terratattle.py --circleci

executors:
    default:
        description: |
            CircleCI Python 3.6.1 image.
        docker:
            - image: circleci/python:3.6.1

commands: {}

examples:
    terratattle:
        usage:
            version: 2.1
            orbs:
              terratattle-orb: terratattle/terratattle-orb@1.0.0
            workflows: 
              use-my-orb:
                jobs:
                  - terratattle-orb/terratattle
